# Generated by Django 4.2.6 on 2023-11-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatuur', models.FloatField()),
                ('CO2', models.IntegerField()),
                ('luchtvochtigheid', models.IntegerField()),
                ('luchtdruk', models.IntegerField()),
            ],
        ),
    ]
