# Generated by Django 4.2.5 on 2023-12-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_luchtdruk_seeders_airquality_and_more'),
        ('dashboard', '0002_seeders_timestamp'),
    ]

    operations = [
    ]
