# Generated by Django 4.2.5 on 2023-12-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_merge_20231220_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seeders',
            old_name='AIRQUALITY',
            new_name='luchtdruk',
        ),
        migrations.RenameField(
            model_name='seeders',
            old_name='HUMIDITY',
            new_name='luchtkwaliteit',
        ),
        migrations.RenameField(
            model_name='seeders',
            old_name='PRESSURE',
            new_name='luchtvochtigheid',
        ),
        migrations.RenameField(
            model_name='seeders',
            old_name='TEMPERATURE',
            new_name='temperatuur',
        ),
    ]
