# Generated by Django 4.2.6 on 2023-11-01 11:50

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_seeders'),
    ]

    operations = [
        migrations.AddField(
            model_name='Seeders',
            name='luchtkwaliteit',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
